[package]
name = "ghostbro-common"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
base64.workspace = true
chacha20poly1305.workspace = true
curve25519-elligator2 = { version = "0.1.0-alpha.2", features = ["elligator2"] }
ed25519-dalek.workspace = true
rand.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
x25519-dalek.workspace = true
